# Upload Studio - Custom Print AZ

client_id = "6a719715f1603fca68e916ae4f7f66e6"
name = "UStudio Custom Print AZ"
application_url = "https://customprintaz.uploadstudio.app.techifyboost.com"
embedded = true
handle = "customprintaz"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "fast-dtf-az.myshopify.com"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products-delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products-update"

[access_scopes]
scopes = "read_customers,read_files,read_orders,read_products,write_draft_orders,write_files,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://customprintaz.uploadstudio.app.techifyboost.com/auth/callback",
  "https://customprintaz.uploadstudio.app.techifyboost.com/api/auth/callback"
]

[app_proxy]
url = "https://customprintaz.uploadstudio.app.techifyboost.com"
subpath = "customizer"
prefix = "apps"

[pos]
embedded = false
