# Upload Studio - Gang Sheet

client_id = "e534fd6a1637a0dc42d7d23fb540495f"
name = "UStudio Gang Sheet"
application_url = "https://gangsheet.uploadstudio.app.techifyboost.com"
embedded = true
handle = "ustudio-gangsheet"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "atlasdtfprint.myshopify.com"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products-delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products-update"

[access_scopes]
scopes = "read_customers,read_files,read_orders,read_products,write_files,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://gangsheet.uploadstudio.app.techifyboost.com/auth/callback",
  "https://gangsheet.uploadstudio.app.techifyboost.com/api/auth/callback"
]

[app_proxy]
url = "https://gangsheet.uploadstudio.app.techifyboost.com"
subpath = "customizer"
prefix = "apps"

[pos]
embedded = false
