# Upload Studio - DTF Print House

client_id = "16744223ead9d1febf910a5a24d48a15"
name = "UStudio DTF Print House"
application_url = "https://dtfprinthouse.uploadstudio.app.techifyboost.com"
embedded = true
handle = "dtfprinthouse"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "e3bd2d-3.myshopify.com"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "products/delete" ]
  uri = "/webhooks/products-delete"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/webhooks/products-update"

[access_scopes]
scopes = "read_customers,read_files,read_orders,read_products,write_draft_orders,write_files,write_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dtfprinthouse.uploadstudio.app.techifyboost.com/auth/callback",
  "https://dtfprinthouse.uploadstudio.app.techifyboost.com/api/auth/callback"
]

[app_proxy]
url = "https://dtfprinthouse.uploadstudio.app.techifyboost.com"
subpath = "customizer"
prefix = "apps"

[pos]
embedded = false
