import { useMatches } from '@remix-run/react'
import { PUBLIC_LEGAL_DOCUMENT_VERSION } from '~/lib/publicLegalPolicy'
export type LegalSection = 'privacy' | 'terms' | 'dpa' | 'gdpr' | 'docs' | 'contact' | 'changelog'
export const legalTitles: Record<LegalSection, string> = {
  privacy: 'Privacy policy', terms: 'Terms of service', dpa: 'Data Processing Agreement', gdpr: 'Privacy requests',
  docs: 'Getting started', contact: 'Support', changelog: 'Release notes',
}
const content: Record<LegalSection, Array<[string, string]>> = {
  privacy: [
    ['Purpose and operator', 'Auto Gang Sheet Upload is an Actual Scope service. It measures finished print files, links them to Shopify orders and calculates the merchant app fee. The confirmed operator appears above; an authentic service address is shown if supplied. Activation requires operator confirmation and the merchant’s explicit acceptance of these processing terms. Applicable local identity/address obligations still apply. Contact info@actualscope.com for privacy questions.'],
    ['Data we need', 'We store uploaded artwork and filenames, dimensions, DPI, product configuration, the store domain, authenticated merchant sessions and access tokens, and order/customer identifiers needed to associate a file with a purchase. Order amounts, capture/refund status and fee records support billing. Buyer names, email addresses, postal addresses and phone numbers are not requested.'],
    ['No visitor profiling', 'There are no browser fingerprints, persistent visitor IDs, visitor sessions, advertising attribution, geolocation collection or session replay. Local upload-resume state and file-content hashes are used only to avoid uploading the same bytes again.'],
    ['Retention', 'Unordered files are deleted after 7 days; ordered files and their upload associations after 90 days from upload creation. Operational upload logs expire after 30 days and audit records after 365 days. Minimal fee keys and verified paid quantities remain while installed for accounting and replay protection. Paid-sheet customer linkage lasts only the merchant-enabled automatic pricing window: a visible 1–12 whole months, default 12, each 30 days. The link is also retained while the original production upload or its export archive exists so customer privacy requests can find an anonymous upload. Hourly bounded cleanup clears older links after those files are deleted; disabling the program clears links no longer needed for files. Customer erasure clears them sooner. Shortening or disabling history cannot be undone by later lengthening. Customer export packages expire after 7 days. Uninstall disables processing immediately and schedules full erasure within 48 hours when the deletion worker and storage are available; failures remain visible and retryable.'],
    ['Recipients and locations', 'Shopify provides store authentication, order facts and app billing. DigitalOcean, LLC hosts this independent app, managed PostgreSQL and Valkey in NYC3, United States. Cloudflare, Inc. stores artwork in private R2 storage with an Eastern North America placement hint; that hint is not a contractual data-residency guarantee. These providers can process service/support/security data in other locations under their applicable terms and transfer safeguards. No artwork is sold or used to train models.'],
    ['Security', 'Authenticated merchant access and mandatory shop-scoped queries restrict administration. Production and identity links are durable bearer capabilities: keep them private until files are deleted under retention or access is invalidated. Temporary direct-storage URLs expire, but that does not expire the production or identity link that supplies them. PostgreSQL, Valkey and R2 provide encrypted storage; external connections use TLS. The independent host keeps application credentials, container data and operational logs on encrypted block storage; working artwork is processed in memory-backed temporary storage. The original operating-system disk is not fully encrypted, and this document does not certify physical sanitization of historical storage or security work as complete.'],
    ['Your rights', 'Ask the merchant or info@actualscope.com for access or erasure. Shopify privacy webhooks trigger durable export and deletion work, including stored files. Minimal order-fee facts remain while installed for duplicate-charge prevention and merchant accounting, without buyer contact details; customer-specific pricing and paid-volume linkages are removed on customer erasure. We do not knowingly solicit children’s personal information.'],
  ],
  terms: [
    ['Agreement and activation', 'The store representative accepts these Terms, the Privacy policy and the Data Processing Agreement in Setup before customer uploads or billing activation. Shopify billing approval is separate permission for charges. The representative warrants authority to act for the store; acceptance records the store, verified Shopify administrator identifier, time, operator identity and document version. Material document or operator changes require acceptance again.'],
    ['What the service does', 'The upload is a finished production sheet. The app measures and prices it; it does not rearrange, nest or combine designs. Quantity is the number of copies printed. The merchant is responsible for printable limits, variant sizes, rates and production quality.'],
    ['App charges', 'The merchant pays 3.5% of attributable captured net merchandise per order, capped at USD 6 per order, through Shopify usage billing. Taxes, shipping and unrelated items are excluded. There is no fixed monthly subscription charge, trial fee or external card collection. A merchant-approved 30-day spending limit applies; an increase requires Shopify approval.'],
    ['Cancellations and refunds', 'Unpaid or cancelled orders are not charged. A full refund before fee collection voids the fee. Already submitted Shopify usage records are not reversible: eligible cancellation/refund cases become auditable credit-review requests. Partial refunds are reviewed manually. Unknown provider outcomes are quarantined, never blindly charged with a new key.'],
    ['Artwork and access', 'Upload only artwork you may lawfully print. You retain ownership and grant the limited permission needed to store, measure, preview and supply it to the merchant. Keep the print and identity links private: they are bearer capabilities. Files are not permanent archives; download production files within the retention period.'],
    ['Service limitations', 'Large or unsupported files may require processing or manual review. No unmeasurable or non-printable file should be orderable through the app. The merchant remains the seller of the physical product and handles shipping, print disputes and buyer refunds. Contact support for app errors or disputed app fees.'],
  ],
  dpa: [
    ['Parties and roles', 'The merchant is the controller (or a processor authorized by its customer). The contracting operator shown above is the processor for customer artwork and related order data. The merchant instructs processing through installation, product settings, customer uploads and order/erasure requests. Operator identity and these terms must be confirmed before activation; an unidentified brand is not a substitute for a contracting party.'],
    ['Scope and instructions', 'Processing covers upload receipt, measurement, preview, private storage, supply of production files to the merchant, order-file matching, merchant-defined pricing and app-fee accounting. Subjects are the merchant’s uploading customers and verified merchant administrators. Data includes submitted artwork/filenames, technical image facts, store/product/order/customer identifiers, paid quantities and relevant capture/refund/fee facts. Buyer contact fields are not requested from Shopify. Artwork can itself contain personal information; the merchant must have a lawful basis and permission to submit it. No unrelated profiling, marketing, sale or model training is authorized.'],
    ['Confidentiality and security', 'The operator limits access to authorized personnel acting for the service and requires confidentiality. Technical controls include shop isolation, authenticated administration, private storage, bounded worker processing and encrypted provider storage/TLS. Production and identity links are durable bearer capabilities and must be kept private until retention deletion or access invalidation; temporary direct-storage URLs expire separately. The merchant must protect production links and its Shopify accounts. Before public release the operator must complete the documented operational access review and address historical credential storage; this draft is not a security certification.'],
    ['Subprocessors and transfers', 'The merchant authorizes DigitalOcean, LLC for United States NYC3 compute/PostgreSQL/Valkey and Cloudflare, Inc. for private R2 artwork storage with an Eastern North America placement hint. Shopify is the merchant-selected commerce platform and supplies app authentication/order/billing services under its own terms. Provider processing can include other locations. The operator uses owner-authorized provider accounts under their service agreements, which incorporate the applicable provider DPAs and transfer safeguards by reference. A separately signed PDF is not a condition when those incorporated terms apply. Applicable jurisdiction and processing instructions still govern. Material subprocessor changes are notified to the merchant before use, with an opportunity to object and discontinue the service.'],
    ['Customer rights and assistance', 'The merchant determines required customer notices, lawful basis and any applicable consent or sharing opt-outs. The operator assists with authenticated access, export and erasure through Shopify privacy webhooks and the merchant Privacy requests page, and will notify the merchant of direct customer requests rather than disclose files to an unverified requester. Technical measurement is not a personal credit, employment or other significant life-impacting decision; merchant volume discounts use paid-sheet history and are disclosed as pricing.'],
    ['Retention and return/deletion', 'The Privacy policy specifies file/log/export lifetimes and the bounded customer-history linkage used for merchant pricing and production-file privacy discovery. Customer erasure removes files and customer pricing/linkages after existing upload capabilities expire; minimal non-contact fee and verified paid-sheet facts remain for accounting and replay protection while installed, without retaining the buyer link indefinitely. Uninstall revokes processing and schedules full shop/object-prefix deletion within 48 hours under normal operation. Failures remain visible and are retried. Managed database backups expire on the provider’s seven-day recovery cycle; a restored database must replay completed erasures before serving requests.'],
    ['Incidents, review and end of service', 'The operator notifies the merchant without undue delay after confirming a personal-data breach affecting its service, provides reasonably available facts and cooperates on required notices. It provides reasonable information demonstrating these processing controls and addresses unlawful processing instructions with the merchant. Contact info@actualscope.com for processing instructions, security incidents and agreement questions. The merchant can export available production files before uninstall; uninstall starts the published deletion process.'],
  ],
  gdpr: [
    ['Request access', 'Contact your merchant or info@actualscope.com. Shopify customers/data_request events create an export of the stored customer-associated file and order records, available to the authenticated merchant for 7 days.'],
    ['Request erasure', 'customers/redact blocks the affected uploads, waits for existing direct-upload capabilities to expire, then deletes associated files and records. shop/redact removes the store prefix, incomplete multipart uploads, sessions and store records. Processing failures are retained for retry rather than acknowledged as completed.'],
    ['Merchant visibility', 'The Privacy requests page shows queued, processing, completed or retrying requests and downloadable exports. No customer email is needed to locate a request: Shopify supplies the signed customer/order identifiers.'],
  ],
  docs: [
    ['1. Configure a product', 'Open Setup, select an existing Shopify product, choose variant sheets or measured-length pricing and enter the printable width. The visible defaults are 22.5 inches wide, 240 inches maximum length for custom pricing, and 0.02 inch export tolerance. Custom pricing requires your own per-inch rate.'],
    ['2. Approve billing and enable the block', 'Approve the Shopify usage subscription on Billing, then add the matching app block in the Shopify theme editor on the product template. No theme file edits or external account are required. The app proxy is /apps/customizer by default; if you change it in Shopify, update the block API-path setting.'],
    ['3. Print the customer’s file', 'Upload, measurement, sheet/price confirmation and cart preparation preserve the three order properties: Print Ready, Sheet Identity and DPI. Use Print Ready for production; use Sheet Identity to inspect the measurement. Checkout display is optional, and the checkout-step target requires Shopify Plus.'],
    ['Measurement', 'The existing finished-sheet orientation policy chooses the printable orientation that consumes the least film. PNG/JPEG headers are validated on the server before price authority accepts them. Other formats use bounded image workers. A file over the printable width or length ceiling is rejected, not split or nested.'],
  ],
  contact: [['Contact support', 'Email info@actualscope.com with your shop domain, upload or Shopify order number and a brief description. Do not send customer payment details or unnecessary personal data. Support messages are used only to resolve your request.']],
  changelog: [['Public application branch — 9 October 2026', 'Independent single-app architecture, durable multishop sessions, mandatory row isolation, bounded fair workers, Shopify usage billing, removal of visitor tracking and durable privacy workflows. This page describes the public branch; registration, hosted deployment and App Store review remain separate release gates.']],
}

export function PublicLegalContent({ section }: { section: LegalSection }) {
  const matches = useMatches()
  const operator = matches.map(match => (match.data as { publicLegalOperator?: { name: string; address: string; ready: boolean } } | undefined)?.publicLegalOperator).find(Boolean)
  return <article>
    <h1>{legalTitles[section]}</h1>
    <p>Auto Gang Sheet Upload · Processing terms version {PUBLIC_LEGAL_DOCUMENT_VERSION} · {operator?.ready ? 'effective upon merchant acceptance' : 'release review pending'}</p>
    {operator?.name && <p>Contracting operator: {operator.name}. {operator.address}</p>}
    {!operator?.ready && ['privacy', 'terms', 'dpa'].includes(section) && <p role="note">Public activation is not available until the operator identity and processing terms are confirmed. These pages do not assert that merchant/provider agreements have already been executed.</p>}
    {content[section].map(([title, body]) => <section key={title} style={{ marginBlock: '1.5rem' }}><h2>{title}</h2><p style={{ lineHeight: 1.65 }}>{body}</p></section>)}
    <p><a href="mailto:info@actualscope.com">info@actualscope.com</a></p>
  </article>
}
