


api_version = "2026-10"

[[extensions]]
name = "Upload Design Display"
handle = "checkout-upload-display"
type = "ui_extension"



[[extensions.targeting]]
module = "./src/CheckoutLineItem.jsx"
target = "purchase.checkout.cart-line-item.render-after"


[[extensions.targeting]]
module = "./src/CheckoutLineItem.jsx"
target = "purchase.thank-you.cart-line-item.render-after"

[extensions.capabilities]
api_access = true
